config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  post 'sign_out', to: 'sessions#sign_out'

  resources :posts, only: [:index, :show]

  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def auth_token
    { authorization: cookies[:token] }
  end

  def identify_user
    redirect_to new_session_path unless cookies[:token].present?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :identify_user

  def index
    response = HTTParty.get("#{ENV['BLOG_1_URL']}/api/v1/posts", headers: auth_token)
    @posts = JSON.parse(response.to_s)['data']
  end

  def show
    response = HTTParty.get("#{ENV['BLOG_1_URL']}/api/v1/posts/#{params[:id]}", headers: auth_token)
    @post = JSON.parse(response.to_s)['data']
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to posts_path if cookies[:token].present?
  end

  def create
    session_request = HTTParty.post("#{ENV['BLOG_1_URL']}/api/v1/sessions",
      body: {
        email: params[:session][:email],
        password: params[:session][:password]
      }
    )

    if session_request.code.to_i == 200
      token = JSON.parse(session_request.body).dig('data', 'attributes', 'token')
      cookies[:token] = token

      redirect_to posts_path
    else
      redirect_to new_session_path
    end
  end

  def sign_out
    cookies[:token] = nil
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?
    cookies[:token].present?
  end
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IubendaBlog2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user?
      = link_to 'Sign out', sign_out_path, method: :post

    = yield

app/views/posts/index.html.haml
%h2
  Your posts

- @posts.each do |post|
  - if post.dig('attributes', 'cover_image')
    %p
      = link_to image_tag(post['attributes']['cover_image']), post_path(post['id'])
  %p
    %b
      = link_to post['attributes']['title'], post_path(id: post['id'])
  %small
    %em
      = post['attributes']['created_at']

app/views/posts/show.html.haml
- if @post.dig('attributes', 'cover_image')
  %p
    = image_tag @post['attributes']['cover_image']
%p
  %b
    = @post['attributes']['title']
%small
  %em
    = @post['attributes']['created_at']
%p
  = @post['attributes']['description']
%p
  = link_to 'Back', posts_path